### ISSUE TITLE
backupHostList is not defined

### ISSUE THREAD

**Issue by umernalla** [thomsonreuters/websocket-api#25]
Hi all,
Please note that the market_price_rdpgw_service_discovery.py uses an undefined variable backupHostList .
Running the example generates the following error:
Traceback (most recent call last):
  File "C:\Refinitiv\websocket-api-master\Applications\Examples\RDP\python\market_price_rdpgw_service_discovery.py", line 555, in <module>
    if not query_service_discovery():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Refinitiv\websocket-api-master\Applications\Examples\RDP\python\market_price_rdpgw_service_discovery.py", line 257, in query_service_discovery
    backupHostList.append(response_json['services'][index]['endpoint'] + ":" +
    ^^^^^^^^^^^^^^
NameError: name 'backupHostList' is not defined

**Comment by vlevendel** [comment]
Fixed with [commit ](https://github.com/Refinitiv/websocket-api/commit/11858465665ef0875ff387e431287c21f4a468a1)
